# Generated by Django 3.2.8 on 2021-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_to_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_to_customer',
            field=models.BooleanField(default=True),
        ),
    ]
