# Generated by Django 3.2.8 on 2021-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('X', 'Cancelled'), ('C', 'Completed')], default='S', max_length=2),
        ),
    ]
