# Generated by Django 3.2.8 on 2021-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(default='11:00:am'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('X', 'Cancelled'), ('R', 'Ready for pickup'), ('C', 'Completed')], default='S', max_length=2),
        ),
    ]
